# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker compose reference guide at
# https://docs.docker.com/compose/compose-file/

# Here the instructions define your application as two services called "todo-app" and “todo-database”
# The service “todo-app” is built from the Dockerfile in the /app directory,
# and the service “todo-database” uses the official MongoDB image 
# from Docker Hub - https://hub.docker.com/_/mongo. 
# You can add other services your application may depend on here.

services:
  vectors:
    image: "redis/redis-stack-server"
    volumes:
      - ./redis_data:/data:rw
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    restart: always #unless-stopped
volumes:
  redis_data:
