[project]
name = "embed"
version = "0.1.0"
[build-system]
requires = ["setuptools>=61.0", "onnxruntime", "tokenizers", "mobileclip @ git+https://github.com/apple/ml-mobileclip"]
build-backend = "setuptools.build_meta"